/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2020-07-16 19:04:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Arrays;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substringBefore", org.apache.taglibs.standard.functions.Functions.class, "substringBefore", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/jsp/../resources/js/reportfunctions.js", Long.valueOf(1594926139558L));
    _jspx_dependants.put("jar:file:/C:/Users/gce/.m2/repository/org/springframework/spring-webmvc/5.1.10.RELEASE/spring-webmvc-5.1.10.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1569683330000L));
    _jspx_dependants.put("file:/C:/Users/gce/.m2/repository/org/springframework/spring-webmvc/5.1.10.RELEASE/spring-webmvc-5.1.10.RELEASE.jar", Long.valueOf(1571233170982L));
    _jspx_dependants.put("jar:file:/C:/Users/gce/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("file:/C:/Users/gce/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1571152422633L));
    _jspx_dependants.put("/WEB-INF/jsp/../resources/js/SystemClock.js", Long.valueOf(1594216159104L));
    _jspx_dependants.put("jar:file:/C:/Users/gce/.m2/repository/org/springframework/spring-webmvc/5.1.10.RELEASE/spring-webmvc-5.1.10.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1569683330000L));
    _jspx_dependants.put("jar:file:/C:/Users/gce/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153399482000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fid_005faction_005fModelAttribute;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fid_005faction_005fModelAttribute = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fid_005faction_005fModelAttribute.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<html>\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("<head>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<title>JBA Shipping inc.</title>\r\n");
      out.write("\t<script>");
      out.write("/*!\r\n");
      out.write(" * JavaScript Methods (https://github.com/Aaron-Larch/Websight-Protobuild)\r\n");
      out.write(" * Copyright 2020-2025 GCE, Inc.\r\n");
      out.write(" * Created by Aaron Larch\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("\t// Get a modal\r\n");
      out.write("\tthis.loadModal = function(input){\r\n");
      out.write("\t\t$(\"#AssineParamiters\").modal().on('shown.bs.modal', function (e) {loadValues(\".PopUpModal\", \".CreateNewRecord\", input)});\r\n");
      out.write("\t\tload_page('/WEB-INF/ModelLibrary.jsp #container');\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tthis.getModal = function(){\r\n");
      out.write("\t\t$(\"#CreateNewRecord\").modal().on('shown.bs.modal');\r\n");
      out.write("\t\tload_page('/WEB-INF/ModelLibrary.jsp #container');\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t//function to call popup window\r\n");
      out.write("\tthis.loadPopUp =function (input){\r\n");
      out.write("\t\t$(\"#PopUpModal\").modal().on('shown.bs.modal', function (e) {loadContent(input);});\r\n");
      out.write("\t\tload_page('/WEB-INF/ModelLibrary.jsp #container');\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t//Switch states button\r\n");
      out.write("\tthis.SwichLoadout= function(a){\r\n");
      out.write("\t\tif(a==1){\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".Populate\"), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".display\"), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".Populate\"), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll('.display'), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t//Check all function\r\n");
      out.write("\tthis.checkAll=function(source) {\r\n");
      out.write("\t\t  checkboxes = document.getElementsByName('operation');\r\n");
      out.write("\t\t  for(var i=0; i<checkboxes.length; i++) {\r\n");
      out.write("\t\t    checkboxes[i].checked = source.checked;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\r\n");
      out.write("\tthis.renderChart();\r\n");
      out.write("})\t\r\n");
      out.write("\r\n");
      out.write("function load_page(url){$('modal-isi-body').load(url) ;}\r\n");
      out.write("\r\n");
      out.write("//Display a combination of classes based of a given variabule\r\n");
      out.write("function loadValues(class1, class2, flag){\r\n");
      out.write("\tif(flag==\"page1\"){\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(class1), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(class2), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t}else if(flag==\"page2\"){\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(class2), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(class1), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//Select a string from an array of strings based on user input \r\n");
      out.write("function loadContent(input) {\r\n");
      out.write("\tdocument.getElementById(\"Display\").value = \"\";\r\n");
      out.write("\t//convert string into an array of strings\r\n");
      out.write("\tvar JsArray = document.getElementById('DisplayValue').innerHTML;\r\n");
      out.write("\tvar block = JsArray.substring(1, JsArray.length-1);\r\n");
      out.write("\tvar string = block.split(\"break\");\r\n");
      out.write("\tif(input > 0){ //Search array\r\n");
      out.write("\t\tvar quickfix=string[input].substring(2, string[input].length);\r\n");
      out.write("\t\tdocument.getElementById('Display').value=quickfix;\r\n");
      out.write("\t}else{document.getElementById('Display').value=string[input];}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function loadChannel(cl1, cl2, cl3, cl4, flag){\r\n");
      out.write("\tif(flag==\"Step1\"){\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl1), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl2), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl3), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl4), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t}else if(flag==\"Step2\"){\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl4), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl2), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl3), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl1), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t}else if(flag==\"Step3\"){\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl4), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl1), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl2), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl3), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl4), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl1), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl3), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t[].forEach.call(document.querySelectorAll(cl2), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function buildReport(\r\n");
      out.write("\t\txAxsis,\r\n");
      out.write("\t\tbellData,\r\n");
      out.write("\t\thighData,\r\n");
      out.write("\t\tlowData,\r\n");
      out.write("\t\tboxData,\r\n");
      out.write("\t\tbarXAxis,\r\n");
      out.write("\t\tHistogramData) {\r\n");
      out.write("\t/*Chart program layouts as found on https://www.chartjs.org/samples/latest/*/\r\n");
      out.write("\t new Chart(\"BellcurveChart\", {\r\n");
      out.write("\t\t  type: 'line',\r\n");
      out.write("\t\t  data: {\r\n");
      out.write("\t\t    labels: xAxsis,\r\n");
      out.write("\t\t    datasets: [{ \r\n");
      out.write("\t\t        data: bellData,\r\n");
      out.write("\t\t        label: document.getElementById(\"divName\").innerHTML,\r\n");
      out.write("\t\t        borderColor: \"#3e95cd\",\r\n");
      out.write("\t\t        fill: false\r\n");
      out.write("\t\t      }]\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  options: {\r\n");
      out.write("\t\t    title: {\r\n");
      out.write("\t\t      display: true,\r\n");
      out.write("\t\t      text: 'Bell Curve Graph'\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t \r\n");
      out.write("\t new Chart(\"HighLineGraph\", {\r\n");
      out.write("\t\t  type: 'line',\r\n");
      out.write("\t\t  data: {\r\n");
      out.write("\t\t    labels: xAxsis,\r\n");
      out.write("\t\t    datasets: [{ \r\n");
      out.write("\t\t        data: highData,\r\n");
      out.write("\t\t        label: document.getElementById(\"divName\").innerHTML,\r\n");
      out.write("\t\t        borderColor: \"#3e95cd\",\r\n");
      out.write("\t\t        fill: false\r\n");
      out.write("\t\t      }]\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  options: {\r\n");
      out.write("\t\t    title: {\r\n");
      out.write("\t\t      display: true,\r\n");
      out.write("\t\t      text: 'Data Graph from high to low'\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t \r\n");
      out.write("\t new Chart(\"LowLineGraph\", {\r\n");
      out.write("\t\t  type: 'line',\r\n");
      out.write("\t\t  data: {\r\n");
      out.write("\t\t    labels: xAxsis,\r\n");
      out.write("\t\t    datasets: [{ \r\n");
      out.write("\t\t        data: lowData,\r\n");
      out.write("\t\t        label: document.getElementById(\"divName\").innerHTML,\r\n");
      out.write("\t\t        borderColor: \"#3e95cd\",\r\n");
      out.write("\t\t        fill: false\r\n");
      out.write("\t\t      }]\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  options: {\r\n");
      out.write("\t\t    title: {\r\n");
      out.write("\t\t      display: true,\r\n");
      out.write("\t\t      text: 'Data Graph from low to high'\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t \r\n");
      out.write("\t new Chart(\"HistogramChart\", {\r\n");
      out.write("\t\t  type: 'bar',\r\n");
      out.write("\t\t  data: {\r\n");
      out.write("\t\t    labels: barXAxis,\r\n");
      out.write("\t\t    datasets: [{ \r\n");
      out.write("\t\t        data: HistogramData,\r\n");
      out.write("\t\t        label: document.getElementById(\"divName\").innerHTML,\r\n");
      out.write("\t\t        borderColor: \"#3e95cd\",\r\n");
      out.write("\t\t        fill: false\r\n");
      out.write("\t\t      }]\r\n");
      out.write("\t\t  },\r\n");
      out.write("\t\t  options: {\r\n");
      out.write("\t\t    title: {\r\n");
      out.write("\t\t      display: true,\r\n");
      out.write("\t\t      text: 'Histogram Chart'\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t \r\n");
      out.write("\t var chart = new CanvasJS.Chart(\"BoxandWhisker\", {\r\n");
      out.write("\t\t\ttitle:{\r\n");
      out.write("\t\t\t\ttext: \"Box And Whisker Plot\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\taxisY: {\r\n");
      out.write("\t\t\t\tinterval: 40\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdata: [{\r\n");
      out.write("\t\t\t\ttype: \"boxAndWhisker\",\r\n");
      out.write("\t\t\t\tupperBoxColor: \"#FFC28D\",\r\n");
      out.write("\t\t\t\tlowerBoxColor: \"#9ECCB8\",\r\n");
      out.write("\t\t\t\tcolor: \"black\",\r\n");
      out.write("\t\t\t\tdataPoints: [\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t{ label: document.getElementById(\"divName\").innerHTML, y: boxData }\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\t}]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tchart.render();\r\n");
      out.write("}\r\n");
      out.write("function chartslide(data){\r\n");
      out.write("\t$(document).ready(function(){renderChart(data);});\r\n");
      out.write("\tvar canvas = document.querySelector('canvas');\r\n");
      out.write("\tfitToContainer(canvas);\r\n");
      out.write("\r\n");
      out.write("\tfunction renderChart(input) {\r\n");
      out.write("\t\t/*Chart program layouts as found on https://www.chartjs.org/samples/latest/*/\r\n");
      out.write("\t\tvar chart = new Chart(\"chartContainer\", { \r\n");
      out.write("\t\t\ttype: 'line',\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\tlabels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],\r\n");
      out.write("\t\t\t\t\tdatasets: [{ \r\n");
      out.write("\t\t\t\t\t\tdata: input,\r\n");
      out.write("\t\t\t\t\t\tlabel: 'My first dataset',\r\n");
      out.write("\t\t\t\t\t\tborderColor: \"#3e95cd\",\r\n");
      out.write("\t\t\t\t\t\tfill: false\r\n");
      out.write("\t\t\t\t\t}]\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\toptions: {\r\n");
      out.write("\t\t\t\t\ttitle: {\r\n");
      out.write("\t\t\t\t\t\tdisplay: true,\r\n");
      out.write("\t\t\t\t\t\ttext: 'This site can also track Large volumes of data over time and place them into graphs using CharJS software'\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\tchart.render();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fitToContainer(canvas){\r\n");
      out.write("\t\t// Make it visually fill the positioned parent\r\n");
      out.write("\t\tcanvas.style.width ='100%';\r\n");
      out.write("\t\tcanvas.style.height='100%';\r\n");
      out.write("\t\t// ...then set the internal size to match\r\n");
      out.write("\t\tcanvas.width  = canvas.offsetWidth;\r\n");
      out.write("\t\tcanvas.height = canvas.offsetHeight;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function AnimateSlide(){\r\n");
      out.write("\tvar Index = 0;\r\n");
      out.write("\tcarousel();\r\n");
      out.write("\r\n");
      out.write("\tfunction carousel() {\r\n");
      out.write("\t\tvar i;\r\n");
      out.write("\t\tvar x = document.getElementsByClassName(\"ProductSlides\");\r\n");
      out.write("\t\tfor (i = 0; i < x.length; i++) {\r\n");
      out.write("\t\t\tx[i].style.display = \"none\";  \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tIndex++;\r\n");
      out.write("\t\tif (Index > x.length) {Index = 1}    \r\n");
      out.write("\t\tx[Index-1].style.display = \"block\";  \r\n");
      out.write("\t\tsetTimeout(carousel, 4000); // Change image every 4 seconds\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\" https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://canvasjs.com/assets/script/canvasjs.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".Site_Features_List {\r\n");
      out.write("  width: 1100px;\r\n");
      out.write("  height: 350px;\r\n");
      out.write("  left: 8px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  border: 1px solid black;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  }\r\n");
      out.write(".myslides, .ProductSlides{\r\n");
      out.write("\twidth: 1100px;\r\n");
      out.write("\tobject-fit: cover;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("\ttransition: all 1s;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("\t\r\n");
      out.write("  }\r\n");
      out.write(".SlideText {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 89%;\r\n");
      out.write("\tleft: 8px;\r\n");
      out.write("\twidth: 210px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tfont-size:20px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("\ttext-indent: 20px;\r\n");
      out.write("  }\r\n");
      out.write("#pic{width: 100%;}\r\n");
      out.write("\r\n");
      out.write(".ProductSlides.shifting {\r\n");
      out.write("\ttransition: right .2s ease-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 0;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  background-color: #111;\r\n");
      out.write("  overflow-x: hidden;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("  padding-top: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav a {\r\n");
      out.write("  padding: 8px 8px 8px 32px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("  color: #818181;\r\n");
      out.write("  display: block;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav a:hover {\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav .closebtn {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 25px;\r\n");
      out.write("  font-size: 36px;\r\n");
      out.write("  margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-height: 450px) {\r\n");
      out.write("  .sidenav {padding-top: 15px;}\r\n");
      out.write("  .sidenav a {font-size: 18px;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".clear { clear:both; }\r\n");
      out.write("#CenterLine{\r\n");
      out.write("  display: block;\r\n");
      out.write("  margin-left: auto;\r\n");
      out.write("  margin-right: auto;\r\n");
      out.write("}\r\n");
      out.write("#SubImage{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("    margin-right: auto; \r\n");
      out.write("    width: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mySlides {display:none}\r\n");
      out.write(" .badge {\r\n");
      out.write("     border-radius: 0;\r\n");
      out.write("     font-size: 12px;\r\n");
      out.write("     line-height: 1;\r\n");
      out.write("     padding: .375rem .5625rem;\r\n");
      out.write("     font-weight: normal;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" .badge.badge-pill {\r\n");
      out.write("     border-radius: 10rem;\r\n");
      out.write("     background-color: transparent;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" .badge.badge-outline-info {\r\n");
      out.write("     color: #A9A9A9;\r\n");
      out.write("     border: 1px solid #A9A9A9\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .badge:hover{\r\n");
      out.write(" \tcursor:pointer;\r\n");
      out.write(" \tbackground-color: #A9A9A9;\r\n");
      out.write(" }\r\n");
      out.write(".badge.dotfill{ background-color: #A9A9A9;}\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h2>Insert into here a fancy page to sell the compony and what it dose</h2>\r\n");
      out.write("    <div id=\"mySidenav\" class=\"sidenav\">\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\r\n");
      out.write("  <a onclick=\"switchStateBtn('Step1')\" href=\"javascript:void(0)\">About</a>\r\n");
      out.write("  <a onclick=\"switchStateBtn('Step2')\" href=\"javascript:void(0)\">Services</a>\r\n");
      out.write("  <a onclick=\"switchStateBtn('Step3')\" href=\"javascript:void(0)\">Partners</a>\r\n");
      out.write("  <a href=\"#\">Contact</a>\r\n");
      out.write("  ");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <a id=\"LoadFile\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${StartURL }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >Login</a>.\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<span style=\"font-size:30px; cursor:pointer;\" onclick=\"openNav()\">&#9776; Welcome to the JBA Food Shipping & Tracking</span>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"Placeholder\" class=\"slideshow\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${test}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t<div id=\"slider\" class=\"Site_Features_List\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t<canvas class=\"ProductSlides\" id=\"chartContainer\"></canvas>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"Placeholder\" class=\"services\">\r\n");
      out.write("\t\t<div id=\"slider\" class=\"Site_Features_List\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t<canvas class=\"myslides\" id=\"chartContainer\"></canvas>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width:100%\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div Class=\"AboutSite\">\r\n");
      out.write("\t\t<img id=\"CenterLine\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/FixedAssets/ComponyLogo.png\" alt=\"Logo\" width=\"300\" height=\"200\"/>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<img id=\"CenterLine\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/FixedAssets/AaronLarch.jpg\" alt=\"Founder\" width=\"800\" height=\"900\"/>\r\n");
      out.write("\t\t<p style=\"text-align:center;\">This is our Co-founder and CEO. Aaron Larch Is a GCE Trainee built this website from scratch and designed\r\n");
      out.write("\t\t All of the features, testing, and Page displays<br>\r\n");
      out.write("\t\tHe then added an exsternal email server, added an exsternal SQL database, made a data tracker and analyser, \r\n");
      out.write("\t\tand with the help from his co founder Built a Reports page.<br>\r\n");
      out.write("\t\tClick Here to see what the sight has to offer:</p>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\tinsert button here.\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div id=\"SubImage\">\r\n");
      out.write("\t\t\t<img id=\"Cofounder\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/FixedAssets/BrianRodewald1.jpg\" \r\n");
      out.write("\t\t\t\tstyle=\"float: left; margin-right: 15px;\" alt=\"Co-Founder\" width=\"350\" height=\"450\"/>\r\n");
      out.write("\t\t\t<h2><br><br>\r\n");
      out.write("\t\t\tThis is our Sites co-founder</h2>\r\n");
      out.write("\t\t\t<p style=\"text-align:center;\"> Co-founder Brian built 2 web pages for this sight. He \r\n");
      out.write("\t\t\tDesinged part of the logic behind the Graphing software as well as cleaned up chart data generating subrutines.\r\n");
      out.write("\t\t\tHe also created the basic layouts for the table display page where the reports are displayed</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div><br><br><br>\r\n");
      out.write("\t\t<div id=\"SubImage\">\r\n");
      out.write("\t\t\t<img id=\"Add\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/FixedAssets/ShopingInterface.PNG\" \r\n");
      out.write("\t\t\t\tstyle=\"float: right; margin-left: 15px;\" alt=\"SamplePage\" width=\"650\" height=\"325\"/>\r\n");
      out.write("\t\t\t<p style=\"text-align:Center;\"><br>\r\n");
      out.write("\t\t\tThis project started in march 2019 and went through several \r\n");
      out.write("\t\t\tinterations and redesigns as features were added and the sight exspanded to include more content and features. Throghout the\r\n");
      out.write("\t\t\tevolution of this project many chalenges were overcome giving way to new code techniques and improving user security and interface.\r\n");
      out.write("\t\t\tWith each challenge the code improved in quility not just for the curent product but for futuer changes as well<br>\r\n");
      out.write("\t\t\tAdded Features include: <br>\r\n");
      out.write("\t\t\timplamenting password tokens<br>\r\n");
      out.write("\t\t\tconversion from JerseyAP to spring boot<br>\r\n");
      out.write("\t\t\toutomated Creation of a Large number data generator<br>\r\n");
      out.write("\t\t\ta .Zip conversion/compression system<br>\r\n");
      out.write("\t\t\tBlob Data storage of java objects<br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div><br><br>\r\n");
      out.write("\t\t<p  style=\"text-align:Center;\">To contact us for an interview please call us at 111-222-3333 or go to a place that dose not exist</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_spring_005furl_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("<div class=\"page\">\r\n");
      out.write("    <header>\r\n");
      out.write("      <h1>LOLCAT CLOCK</h1>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <h4>\r\n");
      out.write("      I CAN HAZ TIME?? <br>\r\n");
      out.write("      <span id=\"clock\">Clock goes here</span>\r\n");
      out.write("    </h4>\r\n");
      out.write("\r\n");
      out.write("    <img id=\"lolcatImage\" src=\"https://s3.amazonaws.com/media.skillcrush.com/skillcrush/wp-content/uploads/2016/08/normalTime.jpg\" alt=\"lolcat\">\r\n");
      out.write("\r\n");
      out.write("    <blockquote id=\"timeEvent\">This is where time events are reported</blockquote>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    set Wake Up Time\r\n");
      out.write("    <select id=\"wakeUpTimeSelector\">\r\n");
      out.write("      <option value=\"1\">1 AM - 2AM</option>\r\n");
      out.write("      <option value=\"2\">2 AM - 3AM</option>\r\n");
      out.write("      <option value=\"3\">3 AM - 4AM</option>\r\n");
      out.write("      <option value=\"4\">4 AM - 5AM</option>\r\n");
      out.write("      <option value=\"5\">5 AM - 6AM</option>\r\n");
      out.write("      <option value=\"6\">6 AM - 7AM</option>\r\n");
      out.write("      <option value=\"7\">7 AM - 8AM</option>\r\n");
      out.write("      <option value=\"8\" selected>8 AM - 9AM</option>\r\n");
      out.write("      <option value=\"9\">9 AM - 10AM</option>\r\n");
      out.write("      <option value=\"10\">10 AM - 11AM</option>\r\n");
      out.write("      <option value=\"11\">11 AM - 12PM</option>\r\n");
      out.write("      <option value=\"12\">12 PM - 1PM</option>\r\n");
      out.write("      <option value=\"13\">1 PM - 2PM</option>\r\n");
      out.write("      <option value=\"14\">2 PM - 3PM</option>\r\n");
      out.write("      <option value=\"15\">3 PM - 4PM</option>\r\n");
      out.write("      <option value=\"16\">4 PM - 5PM</option>\r\n");
      out.write("      <option value=\"17\">5 PM - 6PM</option>\r\n");
      out.write("      <option value=\"18\">6 PM - 7PM</option>\r\n");
      out.write("      <option value=\"19\">7 PM - 8PM</option>\r\n");
      out.write("      <option value=\"20\">8 PM - 9PM</option>\r\n");
      out.write("      <option value=\"21\">9 PM - 10PM</option>\r\n");
      out.write("      <option value=\"22\">10 PM - 11PM</option>\r\n");
      out.write("      <option value=\"23\">11 PM - 12AM</option>\r\n");
      out.write("      <option value=\"24\">12 AM - 1AM</option>\r\n");
      out.write("    </select>\r\n");
      out.write("    <br>\r\n");
      out.write("    set Lunch Time\r\n");
      out.write("      <select id=\"lunchTimeSelector\">\r\n");
      out.write("        <option value=\"1\">1 AM - 2AM</option>\r\n");
      out.write("        <option value=\"2\">2 AM - 3AM</option>\r\n");
      out.write("        <option value=\"3\">3 AM - 4AM</option>\r\n");
      out.write("        <option value=\"4\">4 AM - 5AM</option>\r\n");
      out.write("        <option value=\"5\">5 AM - 6AM</option>\r\n");
      out.write("        <option value=\"6\">6 AM - 7AM</option>\r\n");
      out.write("        <option value=\"7\">7 AM - 8AM</option>\r\n");
      out.write("        <option value=\"8\">8 AM - 9AM</option>\r\n");
      out.write("        <option value=\"9\">9 AM - 10AM</option>\r\n");
      out.write("        <option value=\"10\">10 AM - 11AM</option>\r\n");
      out.write("        <option value=\"11\">11 AM - 12PM</option>\r\n");
      out.write("        <option value=\"12\" selected>12 PM - 1PM</option>\r\n");
      out.write("        <option value=\"13\">1 PM - 2PM</option>\r\n");
      out.write("        <option value=\"14\">2 PM - 3PM</option>\r\n");
      out.write("        <option value=\"15\">3 PM - 4PM</option>\r\n");
      out.write("        <option value=\"16\">4 PM - 5PM</option>\r\n");
      out.write("        <option value=\"17\">5 PM - 6PM</option>\r\n");
      out.write("        <option value=\"18\">6 PM - 7PM</option>\r\n");
      out.write("        <option value=\"19\">7 PM - 8PM</option>\r\n");
      out.write("        <option value=\"20\">8 PM - 9PM</option>\r\n");
      out.write("        <option value=\"21\">9 PM - 10PM</option>\r\n");
      out.write("        <option value=\"22\">10 PM - 11PM</option>\r\n");
      out.write("        <option value=\"23\">11 PM - 12AM</option>\r\n");
      out.write("        <option value=\"24\">12 AM - 1AM</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    <br>\r\n");
      out.write("    set Nap Time\r\n");
      out.write("    <select id=\"napTimeSelector\">\r\n");
      out.write("      <option value=\"1\">1 AM - 2AM</option>\r\n");
      out.write("      <option value=\"2\">2 AM - 3AM</option>\r\n");
      out.write("      <option value=\"3\">3 AM - 4AM</option>\r\n");
      out.write("      <option value=\"4\">4 AM - 5AM</option>\r\n");
      out.write("      <option value=\"5\">5 AM - 6AM</option>\r\n");
      out.write("      <option value=\"6\">6 AM - 7AM</option>\r\n");
      out.write("      <option value=\"7\">7 AM - 8AM</option>\r\n");
      out.write("      <option value=\"8\">8 AM - 9AM</option>\r\n");
      out.write("      <option value=\"9\">9 AM - 10AM</option>\r\n");
      out.write("      <option value=\"10\">10 AM - 11AM</option>\r\n");
      out.write("      <option value=\"11\">11 AM - 12PM</option>\r\n");
      out.write("      <option value=\"12\">12 PM - 1PM</option>\r\n");
      out.write("      <option value=\"13\">1 PM - 2PM</option>\r\n");
      out.write("      <option value=\"14\">2 PM - 3PM</option>\r\n");
      out.write("      <option value=\"15\" selected>3 PM - 4PM</option>\r\n");
      out.write("      <option value=\"16\">4 PM - 5PM</option>\r\n");
      out.write("      <option value=\"17\">5 PM - 6PM</option>\r\n");
      out.write("      <option value=\"18\">6 PM - 7PM</option>\r\n");
      out.write("      <option value=\"19\">7 PM - 8PM</option>\r\n");
      out.write("      <option value=\"20\">8 PM - 9PM</option>\r\n");
      out.write("      <option value=\"21\">9 PM - 10PM</option>\r\n");
      out.write("      <option value=\"22\">10 PM - 11PM</option>\r\n");
      out.write("      <option value=\"23\">11 PM - 12AM</option>\r\n");
      out.write("      <option value=\"24\">12 AM - 1AM</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    <br>\r\n");
      out.write("    <button id=\"partyTimeButton\">Party!</button>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("      <p>&copy; Skillcrush 2016</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script>\r\n");
      out.write("  ");
      out.write("var wakeuptime = 7;\r\n");
      out.write("var noon = 12;\r\n");
      out.write("var lunchtime = 12;\r\n");
      out.write("var naptime = lunchtime + 2;\r\n");
      out.write("var partytime;\r\n");
      out.write("var evening = 18;\r\n");
      out.write("var oneSecond = 1000; // Define a second\r\n");
      out.write("\r\n");
      out.write("// Getting it to show the current time on the page\r\n");
      out.write("var showCurrentTime = function()\r\n");
      out.write("{\r\n");
      out.write("    // display the string on the webpage\r\n");
      out.write("    var clock = document.getElementById('clock');\r\n");
      out.write(" \r\n");
      out.write("    var currentTime = new Date();\r\n");
      out.write(" \r\n");
      out.write("    var hours = currentTime.getHours();\r\n");
      out.write("    var minutes = currentTime.getMinutes();\r\n");
      out.write("    var seconds = currentTime.getSeconds();\r\n");
      out.write("    var meridian = \"AM\";\r\n");
      out.write(" \r\n");
      out.write("    // Set hours\r\n");
      out.write("\t  if (hours >= noon)\r\n");
      out.write("\t  {\r\n");
      out.write("\t\t  meridian = \"PM\";\r\n");
      out.write("\t  }\r\n");
      out.write("\r\n");
      out.write("\t  if (hours > noon)\r\n");
      out.write("\t  {\r\n");
      out.write("\t\t  hours = hours - 12;\r\n");
      out.write("\t  }\r\n");
      out.write(" \r\n");
      out.write("    // Set Minutes\r\n");
      out.write("    if (minutes < 10)\r\n");
      out.write("    {\r\n");
      out.write("        minutes = \"0\" + minutes;\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    // Set Seconds\r\n");
      out.write("    if (seconds < 10)\r\n");
      out.write("    {\r\n");
      out.write("        seconds = \"0\" + seconds;\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    // put together the string that displays the time\r\n");
      out.write("    var clockTime = hours + ':' + minutes + ':' + seconds + \" \" + meridian + \"!\";\r\n");
      out.write("    clock.innerText = clockTime;\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("// Getting the clock to increment on its own and change out messages and pictures\r\n");
      out.write("var updateClock = function() \r\n");
      out.write("{\r\n");
      out.write("  var time = new Date().getHours();\r\n");
      out.write("  var messageText;\r\n");
      out.write("  var image = \"https://s3.amazonaws.com/media.skillcrush.com/skillcrush/wp-content/uploads/2016/08/normalTime.jpg\";\r\n");
      out.write("\r\n");
      out.write("  var timeEventJS = document.getElementById(\"timeEvent\");\r\n");
      out.write("  var lolcatImageJS = document.getElementById('lolcatImage');\r\n");
      out.write("  \r\n");
      out.write("  if (time == partytime)\r\n");
      out.write("  {\r\n");
      out.write("    image = \"https://s3.amazonaws.com/media.skillcrush.com/skillcrush/wp-content/uploads/2016/08/partyTime.jpg\";\r\n");
      out.write("    messageText = \"Let's party!\";\r\n");
      out.write("  }\r\n");
      out.write("  else if (time == wakeuptime)\r\n");
      out.write("  {\r\n");
      out.write("    image = \"https://s3.amazonaws.com/media.skillcrush.com/skillcrush/wp-content/uploads/2016/09/cat1.jpg\";\r\n");
      out.write("    messageText = \"Wake up!\";\r\n");
      out.write("  }\r\n");
      out.write("  else if (time == lunchtime)\r\n");
      out.write("  {\r\n");
      out.write("    image = \"https://s3.amazonaws.com/media.skillcrush.com/skillcrush/wp-content/uploads/2016/09/cat2.jpg\";\r\n");
      out.write("    messageText = \"Let's have some lunch!\";\r\n");
      out.write("  }\r\n");
      out.write("  else if (time == naptime)\r\n");
      out.write("  {\r\n");
      out.write("    image = \"https://s3.amazonaws.com/media.skillcrush.com/skillcrush/wp-content/uploads/2016/09/cat3.jpg\";\r\n");
      out.write("    messageText = \"Sleep tight!\";\r\n");
      out.write("  }\r\n");
      out.write("  else if (time < noon)\r\n");
      out.write("  {\r\n");
      out.write("    image = \"https://pbs.twimg.com/profile_images/378800000532546226/dbe5f0727b69487016ffd67a6689e75a.jpeg\";\r\n");
      out.write("    messageText = \"Good morning!\";\r\n");
      out.write("  }\r\n");
      out.write("  else if (time >= evening)\r\n");
      out.write("  {\r\n");
      out.write("    image = \"https://upload.wikimedia.org/wikipedia/commons/8/8c/Cat_sleep.jpg\";\r\n");
      out.write("    messageText = \"Good evening!\";\r\n");
      out.write("  }\r\n");
      out.write("  else\r\n");
      out.write("  {\r\n");
      out.write("    image = \"https://s3.amazonaws.com/media.skillcrush.com/skillcrush/wp-content/uploads/2016/08/normalTime.jpg\";\r\n");
      out.write("    messageText = \"Good afternoon!\";\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  console.log(messageText); \r\n");
      out.write("  timeEventJS.innerText = messageText;\r\n");
      out.write("  lolcatImage.src = image;\r\n");
      out.write("  \r\n");
      out.write("  showCurrentTime();\r\n");
      out.write("};\r\n");
      out.write("updateClock();\r\n");
      out.write("\r\n");
      out.write("// Getting the clock to increment once a second\r\n");
      out.write("setInterval( updateClock, oneSecond);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// Getting the Party Time Button To Work\r\n");
      out.write("var partyButton = document.getElementById(\"partyTimeButton\");\r\n");
      out.write("\r\n");
      out.write("var partyEvent = function()\r\n");
      out.write("{\r\n");
      out.write("    if (partytime < 0) \r\n");
      out.write("    {\r\n");
      out.write("        partytime = new Date().getHours();\r\n");
      out.write("        partyTimeButton.innerText = \"Party Over!\";\r\n");
      out.write("        partyTimeButton.style.backgroundColor = \"#0A8DAB\";\r\n");
      out.write("    }\r\n");
      out.write("    else\r\n");
      out.write("    {\r\n");
      out.write("        partytime = -1;\r\n");
      out.write("        partyTimeButton.innerText = \"Party Time!\";\r\n");
      out.write("        partyTimeButton.style.backgroundColor = \"#222\";\r\n");
      out.write("    }\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("partyButton.addEventListener(\"click\", partyEvent);\r\n");
      out.write("partyEvent(); \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// Activates Wake-Up selector\r\n");
      out.write("var wakeUpTimeSelector =  document.getElementById(\"wakeUpTimeSelector\");\r\n");
      out.write("\r\n");
      out.write("var wakeUpEvent = function()\r\n");
      out.write("{\r\n");
      out.write("    wakeuptime = wakeUpTimeSelector.value;\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("wakeUpTimeSelector.addEventListener(\"change\", wakeUpEvent);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// Activates Lunch selector\r\n");
      out.write("var lunchTimeSelector =  document.getElementById(\"lunchTimeSelector\");\r\n");
      out.write("\r\n");
      out.write("var lunchEvent = function()\r\n");
      out.write("{\r\n");
      out.write("    lunchtime = lunchTimeSelector.value;\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("lunchTimeSelector.addEventListener(\"change\", lunchEvent);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// Activates Nap-Time selector\r\n");
      out.write("var napTimeSelector =  document.getElementById(\"napTimeSelector\");\r\n");
      out.write("\r\n");
      out.write("var napEvent = function()\r\n");
      out.write("{\r\n");
      out.write("    naptime = napTimeSelector.value;\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("napTimeSelector.addEventListener(\"change\", napEvent);\r\n");
      out.write("\r\n");
      out.write("function SlidShow() {\r\n");
      out.write("\t  var i;\r\n");
      out.write("\t  var x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("\t  for (i = 0; i < x.length; i++) {\r\n");
      out.write("\t    x[i].style.display = \"none\";  \r\n");
      out.write("\t  }\r\n");
      out.write("\t  myIndex++;\r\n");
      out.write("\t  if (myIndex > x.length) {myIndex = 1}\r\n");
      out.write("\t  if (myIndex-2 > 0){\r\n");
      out.write("\t\t  x[myIndex-2].style.display = \"block\";\r\n");
      out.write("\t\t  trasision\r\n");
      out.write("\t\t  x[myIndex-1].style.display = \"block\";\r\n");
      out.write("\t  }else{\r\n");
      out.write("\t\t  transisition\r\n");
      out.write("\t\t  x[myIndex-1].style.display = \"block\";\r\n");
      out.write("\t  }  \r\n");
      out.write("\t  setTimeout(carousel, (oneSecond*2)); // Change image every 2 seconds\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("\tchartslide(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Arrays.toString(Data)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\r\n");
      out.write("\tAnimateSlide();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction cloneCanvas(oldCanvas) {\r\n");
      out.write("\r\n");
      out.write("\t    //create a new canvas\r\n");
      out.write("\t    var newCanvas = document.createElement('canvas');\r\n");
      out.write("\t    var context = newCanvas.getContext('2d');\r\n");
      out.write("\r\n");
      out.write("\t    //set dimensions\r\n");
      out.write("\t    newCanvas.width = oldCanvas.width;\r\n");
      out.write("\t    newCanvas.height = oldCanvas.height;\r\n");
      out.write("\r\n");
      out.write("\t    //apply the old canvas to the new one\r\n");
      out.write("\t    context.drawImage(oldCanvas, 0, 0);\r\n");
      out.write("\r\n");
      out.write("\t    //return the new canvas\r\n");
      out.write("\t    return newCanvas;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openNav() {\r\n");
      out.write("\t\tdocument.getElementById(\"mySidenav\").style.width = \"250px\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction closeNav() {\r\n");
      out.write("\t\tdocument.getElementById(\"mySidenav\").style.width = \"0\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction switchStateBtn(input){\r\n");
      out.write("\t\tcloseNav()\r\n");
      out.write("\t\tif(input==\"Step1\"){\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".page\"), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".slideshow\"), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".AboutSite\"), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t}else if(input==\"Step2\"){\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".page\"), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".AboutSite\"), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".slideshow\"), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t}else if(input==\"Step3\"){\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".slideshow\"), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".AboutSite\"), function (i) {i.style.display=\"none\";});\r\n");
      out.write("\t\t\t[].forEach.call(document.querySelectorAll(\".page\"), function (i) {i.style.display=\"block\";});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar slideIndex = 1;\r\n");
      out.write("\tshowDivs(slideIndex);\r\n");
      out.write("\r\n");
      out.write("\tfunction plusDivs(n) {\r\n");
      out.write("\t  showDivs(slideIndex += n);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction currentDiv(n) {\r\n");
      out.write("\t  showDivs(slideIndex = n);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction showDivs(n) {\r\n");
      out.write("\t  var i;\r\n");
      out.write("\t  var x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("\t  var dots = document.getElementsByClassName(\"demo\");\r\n");
      out.write("\t  if (n > x.length) {slideIndex = 1}\r\n");
      out.write("\t  if (n < 1) {slideIndex = x.length}\r\n");
      out.write("\t  for (i = 0; i < x.length; i++) {\r\n");
      out.write("\t    x[i].style.display = \"none\";  \r\n");
      out.write("\t  }\r\n");
      out.write("\t  for (i = 0; i < dots.length; i++) {\r\n");
      out.write("\t    dots[i].className = dots[i].className.replace(\" dotfill\", \" whitespace\");\r\n");
      out.write("\t  }\r\n");
      out.write("\t  x[slideIndex-1].style.display = \"block\";  \r\n");
      out.write("\t  dots[slideIndex-1].className += \" dotFill\";\r\n");
      out.write("\t}\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/jsp/Index.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/jsp/Index.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/Index.jsp(8,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f0_reused = false;
    try {
      _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/Index.jsp(144,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}/login", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/Index.jsp(144,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setVar("StartURL");
      int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
        if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
      _jspx_th_spring_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/Index.jsp(152,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("img");
      // /WEB-INF/jsp/Index.jsp(152,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/Index.jsp(152,3) '${imageUrlList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${imageUrlList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("  \r\n");
            out.write("\t\t\t\t<div id=\"silde\" class=\"ProductSlides\">\r\n");
            out.write("\t\t\t\t\t<img id=\"pic\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/ImageAssets/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"MissingImg\" width=\"800\" height=\"400\"/>\r\n");
            out.write("\t\t\t\t\t<p class=\"SlideText\"><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substringBefore(img, \".\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("</span></p>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/jsp/Index.jsp(164,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("img");
      // /WEB-INF/jsp/Index.jsp(164,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/Index.jsp(164,3) '${imageUrlList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${imageUrlList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("  \r\n");
            out.write("\t\t\t\t<div id=\"silde\" class=\"myslides\">\r\n");
            out.write("\t\t\t\t\t<img id=\"pic\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/ImageAssets/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"MissingImg\" width=\"800\" height=\"400\"/>\r\n");
            out.write("\t\t\t\t\t<p class=\"SlideText\"><span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substringBefore(img, \".\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("</span></p>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/jsp/Index.jsp(175,3) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setBegin(1);
      // /WEB-INF/jsp/Index.jsp(175,3) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imageUrlList.size()+1}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/jsp/Index.jsp(175,3) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVarStatus("count");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t<span class=\"badge demo badge-pill badge-outline-info\" onclick=\"currentDiv(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\">  </span> \r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f1 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f1_reused = false;
    try {
      _jspx_th_spring_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f1.setParent(null);
      // /WEB-INF/jsp/Index.jsp(221,2) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f1.setValue("/TestPage");
      // /WEB-INF/jsp/Index.jsp(221,2) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f1.setVar("invoice");
      int[] _jspx_push_body_count_spring_005furl_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f1 = _jspx_th_spring_005furl_005f1.doStartTag();
        if (_jspx_th_spring_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f1);
      _jspx_th_spring_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fid_005faction_005fModelAttribute.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/jsp/Index.jsp(222,2) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "ModelAttribute", "testVal");
      // /WEB-INF/jsp/Index.jsp(222,2) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("post");
      // /WEB-INF/jsp/Index.jsp(222,2) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${invoice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/Index.jsp(222,2) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setId("my_form");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t<label>Amount Purchased</label>\r\n");
            out.write("\t\t<input type=\"text\" name=\"testVal\" form=\"my_form\" />\r\n");
            out.write("\t\t<button type=\"submit\" class=\"btn btn-primary\" form=\"my_form\">Save</button> \r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fid_005faction_005fModelAttribute.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }
}
